global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'zoocache-integration'
    static_configs:
      - targets: ['host.docker.internal:9090'] # This is where the app will expose metrics locally during tests
